### ISSUE TITLE
Cookies system

### ISSUE THREAD

**Issue by Ethanolzee** [TouchMe-Inc/l4d2_chat_processor_rework#1]
Add cookies system to remember players' choices

**Comment by TouchMe-Inc** [comment]
What exactly do you remember using cookies? Players who need to be locally muted?
The main plugin does not store anything and is only an API, other plugins are an example of working with this API

**Comment by Ethanolzee** [comment]
For instance, if i mute a player, currently how the plugin acts is, it auto unmutes their chat and voice on map switch. Cookies system will permanently assure they remain muted for me, unless if i manually unmute them via menu

Would be a great addition if you could implement this

**Comment by TouchMe-Inc** [comment]
As I wrote above, this repository stores the API and includes plugins that use this API. Any additions must be made independently. Sorry :c
